### PR TITLE
fix: mobile version in the home page

### LINKED ISSUE #1193: UI fix: Mobile version for landing page
Align the mobile design with the desktop design by changing the heading layout and also the numbered list. 
Design: https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=1062%3A9060&mode=design&t=NKHyKvjxXmP7RY5d-1

Image

### PR DESCRIPTION
**Pull request by mhenriette**
# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [ ] Tests have been added or updated to reflect your changes.
- [ ] All tests pass.

---

## Pull Request Details

fix the mobile design on the landing page according to the design

## Breaking Changes
none

## Issues Fixed
#1193 

## Summary by CodeRabbit

- **New Features**
	- Enhanced the layout and appearance of the `Numbered` component for improved visual presentation.
	- Updated text styling in the `MainSection` on the homepage for better readability and aesthetic appeal.

### CODE REVIEW

File: src/components/sections/homepage/Main.tsx [hunk 1]
```diff
@@ -41,7 +41,7 @@ export default function MainSection(): ReactElement {
     <Section type="default" padding="p-0">
       <div className="w-full lg:py-24 pt-24 pb-8">
         <h1 className="lg:text-8xl md:text-6xl text-5xl leading-none tracking-tighter">{t("page.index.main.title")}</h1>
-        <p className="lg:text-8xl md:text-6xl text-2xl py-2 lg:py-0 md:py-0 sm:py-0 text-black lg:text-gray-400 md:text-gray-400 sm:text-gray-400 tracking-tighter leading-none">
+        <p className="lg:text-8xl md:text-6xl text-[40px] py-2 lg:py-0 md:py-0 sm:py-0 text-gray-400 tracking-tighter leading-none">
```
Comment (Odile078) [inline src/components/sections/homepage/Main.tsx:44]: we have this `font-size(40px)` with it's lineHeight  as `text-4.5xl`in the `tailwind.config.js`

**Review by Odile078 — APPROVED** [review]

**Review by serapieTuyishime — APPROVED** [review]

**Comment by techgirlonlinee** [comment]
Screenshot 2024-05-07 at 14 05 02
Screenshot 2024-05-07 at 14 04 59
the dotted lines need to look the same. they need to be consistent because they are the same component

**Review by musayann — APPROVED** [review]
