### PR TITLE
fix: update the metric numbers

### LINKED ISSUE #1239: update metrics on homepage
update community metrics on homepage by retrieving the data from firebase 

here is where all the data needs to be updated

Image

### PR DESCRIPTION
**Pull request by mhenriette**
# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guidelines have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [ ] Tests have been added or updated to reflect your changes.
- [ ] All tests pass.

---

## Pull Request Details

update metrics for:
- users count: 22240
- submission Count: 3595
- feedbacks Count: 8131 

## Breaking Changes

none

## Issues Fixed
#1239 

## Summary by CodeRabbit

- **Enhancements**
  - Updated community statistics with the latest counts.
  - Improved number formatting for better readability using a new digit formatter.

### CODE REVIEW

File: src/components/sections/homepage/_partials/testimonials/CommunityStats.tsx [hunk 1]
```diff
@@ -18,27 +19,37 @@ const stats: Statistic[] = [
...
 export default function CommunityStats() {
   const { t } = useTranslation();
+  const digitFormatter = useMemo(() => new Intl.NumberFormat(), []);
+
+  const formattedStat = useMemo(
+    () =>
+      stats.map((stat: Statistic) => ({
+        ...stat,
+        count: digitFormatter.format(stat.count),
+      })),
```
Comment (mbukeRepo) [inline src/components/sections/homepage/_partials/testimonials/CommunityStats.tsx:44]:
```suggestion
    if (!stats) {
      console.warn('Stats are null or undefined');
      return [];
    }

    return stats.map((stat) => ({
      ...stat,
      count: digitFormatter.format(stat.count),
    }));
```

**Review by mbukeRepo — APPROVED** [review]

**Review by serapieTuyishime — APPROVED** [review]

**Review by musayann — APPROVED** [review]
