### PR TITLE
fix: change the regex to validate emails according to RFC 1034 standard

### LINKED ISSUE #1299: Bug: Emails with a domains and subdomains with more than 7 characters are being prohibited to register.
### Description 

With `"aaaaaa.aaaaaaa@aaaaaaaa.network"` as an example; the email above is not being accepted as a valid email on the platform.

Looking in our codebase, in the `src/components/ui/EmailInput.tsx` file line 45, the regex expression: " /^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$/i" is the validator of all emails. While exploring the regex, it appears that the domain part of the email address only accepts a number of characters between 2 and 5. 

The articles below show the rules that email address should have. 
* https://emaillistvalidation.com/blog/understanding-standard-email-validation-best-practices-and-guidelines/
* https://datatracker.ietf.org/doc/html/rfc1034#section-3.5
* [Best regex for email address pattern validation](https://www.abstractapi.com/guides/email-validation/email-address-pattern-validation#rfc-5322-official-standard-regular-expression-to-validate-email-addresses)

Refer to the above documentation to create a regex syntax that implements the standard email.

### Environment
Operating System: macOS Ventura
Browser and version: Safari 16.5.2
Any relevant hardware information: iPhone 15, Google Pixel

### Expected Behaviour
The mentioned email should be accepted in the email 

### Actual Behaviour
The email address is not accepted as a valid email on the platform

### Steps to reproduce. 
1. Logot of [Dacade](dacade.org) if logged in.\
2. Navigate to the [signup page](https://staging-dacade.netlify.app/signup)
3. Enter the example address given in place of the email
4. generate the password and check the "terms and conditions"
5. Click on the "register" button to create an account. 

### Screenshots

Image

### PR DESCRIPTION
**Pull request by mhenriette**
# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [x] Documentation has been updated to reflect your changes.
- [x] Tests have been added or updated to reflect your changes.
- [x] All tests pass.

## Pull Request Details

This pr modifies email verification regex to validate emails according to RFC 1034 standard 

## Breaking Changes
none

## Issues Fixed
#1299 

## Other Relevant Information
none

### CODE REVIEW

File: src/pages/signup.tsx [hunk 1]
```diff
@@ -73,7 +95,7 @@ export default function SignupWithInvite(): ReactElement {
     };
     try {
       if (!checkTerms) return;
-      await dispatch(signUp({ locale, payload: { ...signupData } }));
+      dispatch(signUp({ locale, payload: { ...signupData } }));
```
Comment (serapieTuyishime) [inline src/pages/signup.tsx:98]: Why this change?

Comment (mhenriette) [reply src/pages/signup.tsx:98]: await is not doing anything here.

**Review by Jonath-z — APPROVED** [review]

**Review by Odile078 — APPROVED** [review]

**Review by serapieTuyishime — APPROVED** [review]

**Review by musayann — APPROVED** [review]
