### PR TITLE
fix: title colors in the challenge page

### LINKED ISSUE #1199: UI fix: title color on the challenge page
Change the title colors according to this design

Image

https://www.figma.com/file/0BRR6Ch2qbOEUT4zIdmmzg/Dacade-2?type=design&node-id=1072%3A9694&mode=design&t=d69nNRAmMNqURNhU-1

### PR DESCRIPTION
**Pull request by mhenriette**
# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [ ] Documentation has been updated to reflect your changes.
- [ ] Tests have been added or updated to reflect your changes.
- [ ] All tests pass.

---

## Pull Request Details

change the title and subtitle colors in the challenge page

## Breaking Changes
none

## Issues Fixed
#1199 

## Summary by CodeRabbit

- **Style Updates**
	- Enhanced the header text color scheme for better visual hierarchy and readability by adjusting classes based on the presence of `subtitle`.

### CODE REVIEW

**Review by serapieTuyishime — APPROVED** [review]

File: src/components/sections/communities/_partials/Header.tsx [hunk 1]
```diff
@@ -19,22 +19,20 @@ export default function Header({
...
-    "text-gray-900": !subtitle,
   });
 
   return (
     <div>
       <h1 className={headerClassName}>{title}</h1>
       <div className="flex items-start gap-1">
         {subtitle && (
-          <h2 className="text-4xl flex items-center font-normal leading-none md:text-5xl text-default">
+          <h2 className={`text-4xl flex items-center font-normal leading-none md:text-5xl ${title? "text-gray-400": "text-gray-900"}`}>
```
Comment (Odile078) [inline src/components/sections/communities/_partials/Header.tsx:31]: think it will be more readable to use `classNames` here

Comment (mhenriette) [reply src/components/sections/communities/_partials/Header.tsx:31]: classNames comes in handy when you have multiple condition classes , in this case where we only have a single condition, using a ternary operator directly in the className string is often simpler and more straightforward which is readable as well.

**Review by Odile078 — APPROVED** [review]

**Review by musayann — APPROVED** [review]
