### PR TITLE
fix: spacing in challenge card and add course count

### LINKED ISSUE #1208: UI fix: challenge card in community page
Current version of the wrong border, shading, font sizes

1) spacing between each text line in the text on the left side (from the title to the pill, pill to included learning modules) should be 16px (1rem) but is currently 1.5rem 
2) learning module text should be font small (14px) medium weight. it's currently 16px normal weight. also the color should be grey
3) double line on the bottom of the whole box when it should be a single line 
4) border on the right side of the left text box is missing

Current version:
Image

Design:
Image

**Mobile version** 
1) duplicated line on the top should be removed
2) remove margin top on top of the title

Current version: 
Image

Fix: Counting of learning materials
- Call it: "x Learning materials included"
- Count the amount by adding courses and single learning modules together"

### PR DESCRIPTION
**Pull request by mhenriette**
# Submit a pull request

- [x] This is not a duplicate of an existing pull request.
- [x] No existing features have been broken without good reason.
- [x] Your commit messages are detailed
- [x] The code style guideline have been followed.
- [] Documentation has been updated to reflect your changes.
- [ ] Tests have been added or updated to reflect your changes.
- [ ] All tests pass.

---

## Pull Request Details

spacing in the challenge card and adding course + learning modules  count as learning materials 

## Breaking Changes

none

## Issues Fixed

#1208 

## Summary by CodeRabbit

- **New Features**
	- Updated the count and types of learning materials displayed in the ChallengeCard component to include both learning modules and courses.

- **Style Updates**
	- Improved responsiveness of the ChallengeCard component.
	- Adjusted conditional rendering and styling in the Badges component based on challenge properties.
	- Modified padding values in the RewardCertificate component for better visual layout.
	- Enhanced styling of the Rewards section based on specific challenge conditions.

### CODE REVIEW

File: src/components/cards/challenge/Challenge.tsx [hunk 1]
```diff
@@ -62,11 +60,11 @@ export default function ChallengeCard({ data, community, isCourseEnd }: Challeng
       </div>
       <div className="p-6">
         <div className={"mx-auto relative rounded-full mb-5 w-[147px] h-[184px]"}>
-          <Image src={data?.certificateData?.icon} alt="achievement" fill />
+          <Image src={data?.certificateData?.icon} alt="achievement" fill priority />
```
Comment (Samantha-KY) [inline src/components/cards/challenge/Challenge.tsx:63]: why add this priority attribute?

**Review by serapieTuyishime — APPROVED** [review]

**Review by Odile078 — APPROVED** [review]

**Comment by techgirlonlinee** [comment]
the spacing between the title and the pill should be closer than the pill to the description text. please re-check spacing.

**Review by musayann — APPROVED** [review]
